// File generated by FlutterFire CLI.
// Run: flutterfire configure
// to regenerate this file for your Firebase project.
//
// ── HOW TO SET UP ──────────────────────────────────────────────────────────────
// 1. Install FlutterFire CLI:
//      dart pub global activate flutterfire_cli
//
// 2. Log in to Firebase:
//      firebase login
//
// 3. Run in this project root:
//      flutterfire configure
//    → Select your Firebase project (or create one at https://console.firebase.google.com)
//    → Choose platforms: Android, iOS, Web
//    → This file will be auto-regenerated with real values.
//
// 4. Enable Firestore in Firebase Console:
//    Firebase Console → Firestore Database → Create database → Start in test mode
//
// ──────────────────────────────────────────────────────────────────────────────
// TEMPORARY PLACEHOLDER — replace by running `flutterfire configure`
// ──────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKUl0JcvQkVokH2h6C9xXwHnVF2dynvqw',
    appId: '1:728787499626:web:049e2bf45a4f7659942813',
    messagingSenderId: '728787499626',
    projectId: 'fate-ticket-game',
    authDomain: 'fate-ticket-game.firebaseapp.com',
    storageBucket: 'fate-ticket-game.firebasestorage.app',
    measurementId: 'G-LVV528V2M3',
  );

  // ── REPLACE these values with your own from `flutterfire configure` ──────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAorvQfIhxccqpE7Hi_r8WBSVaqyEBs2SU',
    appId: '1:728787499626:android:98fd50522c1cc033942813',
    messagingSenderId: '728787499626',
    projectId: 'fate-ticket-game',
    storageBucket: 'fate-ticket-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.tambola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.tambola',
  );
}